#
#                 Better Shop's Language File
#
#        You Are Free To Change The Values To Your Liking
#
#These messages are what appear in the "Shop Settings" section of shops
#
#     Lines starting with # are comments and will be ignored.

Version: Snapshot-2.1-3

NotificationsOn: '&a&lNotifications &7- &aOn'
NotificationsOff: '&a&lNotifications &7- &cOff'
NotificationsLore: '&e&lLeft Click &7to change shop &dNotifications'

ChangeDescription: '&a&lChange Description'
ChangeDescriptionLore: '&e&lLeft Click &7to change shop &dDescription'

ChangeName: '&a&lChange Name'
ChangeNameLore: '&e&lLeft Click &7to change shop &dName'

ChangeOwner: '&a&lChange Owner'
ChangeOwnerLore: '&e&lLeft Click &7to change shop &dOwner'

Blacklist: '&a&lPlayer Blacklist'
BlacklistLore: '&e&lLeft Click &7to manage &aPlayer Blacklist'

ServerShopOn: '&a&lServer Shop &7- &aOn'
ServerShopOff: '&a&lServer Shop &7- &cOff'
ServerShopLore: '&e&lLeft Click &7to change &dServer Shop Mode'

NPCShopOn: '&a&lNPC Shop &7- &aOn'
NPCShopOff: '&a&lNPC Shop &7- &cOff'
Warning: '&4WARNING:'
DeletedChest: '&cThe Chest &4Will &cBe Deleted'
NPCLore: '&e&lLeft Click &7to change &dNPC Shop Mode'

HolographicOn: '&a&lHolographic Shop &7- &aOn'
HolographicOff: '&a&lHolographic Shop &7- &cOff'
HolographicLore: '&e&lLeft Click &7to change &dHolographic Shop Mode'

Theme: '&e&lClick &7to set the Shop &aTheme'