#
#                 Better Shop's Config File
#
#        You Are Free To Change The Values To Your Liking
#
#     Lines starting with # are comments and will be ignored.
#

Version: Snapshot-2.1-2

####  General  ####

# Have Chest Contents Automatically be Added To The Shop (True/False)
Auto Add: True

# Enable Permissions (True/False)
Permissions: False

# Use Anvil to Name Shop Use Items (True/False)
Anvil: True

# Enable Titles and Subtitles (True/False) (1.8 and Above)
Titles: True

# Toggle Server Metrics
Metrics: True

# Allow use of chests by Shop Owners/using double chests for shops
UseChests: True

# Remove Empty shops after x Days (0 turns it off)
RemoveAfter: 0

#### Shop Options ####

# Toggle the use of selling shops
SellingShops: True

# The default price of all items
DefaultPrice: 5.00

# Maximum Price
MaxPrice: 1000000000.00

# Disable deleting shops by breaking the chest(Can only use /sremove)
DeleteByBreak: True

# Allows players to use shop when closed if they had opened it while the shop was open (True/False)
UseOnClose: False

# Enables Transactions to be visible to the shop owners (May cause startup lag if enabled)
UseTransactions: True

# All stock for a selling item goes to a buying item if it exists
SellToBuy: True

# Limits the amount of stock a player can have (0 = infinite)
StockLimit: 0

# Enable Trades
Trades: True

####  Shop Creation  ####

# Enable Shop Creation Limits (True/False)
Creation Limit: False

# Set Creation Limit
Limit: 3

# Forces players to pay for each shop creation (True/False)
CostOnShops: False

# The cost for each shop creation (Previous must be true)
CostForShops: 19.99


####  NPCs  ####

# Enable NPC Shops (True/False)
EnableNPC: True

# The Type of NPC that a shop can use
NPC:
  Bat: true
  Blaze: true
  Cave Spider: true
  Chicken: true
  Cow: true
  Creeper: true
  Enderman: true
  Endermite: true
  Ghast: true
  Giant: true
  Guardian: true
  Horse: true
  Iron Golem: true
  Magma Cube: true
  Mushroom Cow: true
  Ocelot: true
  Player: true
  Pig: true
  Pig Zombie: true
  Rabbit: true
  Sheep: true
  Silverfish: true
  Skeleton: true
  Slime: true
  Snowman: true
  Spider: true
  Squid: true
  Villager: true
  Witch: true
  Wither: true
  Wolf: true
  Zombie: true

####  World Guard  ####

# If World Guard is detected then players can only create shops in regions with the 'Allow-Shop' flag (True/False)
EnableAllowShopsFlag: False

# Override a region to allow NPCs to spawn (only if Mob-Spawning is disabled in the region. If False, NPCs will not spawn in these regions) (True/False)
NPCOverride: True

####  Holographic Shops  ####

# Enable Holographic shops
HoloShops: True

####  Live Economy  ####

# Enables the ability to use Live Economy
UseLiveEco: True

####  Databases  ####
SQL: False
host: 'localhost'
port: 3306
username: 'root'
password: ''
database: 'bettershops'
prefix: 'bs_'